Content-Type: application/json

{
 "success": true,
 "message": "Necessary objects imported.",
 "tester": 3,
 "parameterNames": [
  "Destination distance (km)",
  "Number of days"
 ],
 "solution": [
  1850.0,
  7.0
 ],
 "objectives": [
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ]
 ],
 "bad_solutions": [],
 "saved_solutions": [
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  [
   1850.0,
   7.0
  ]
 ],
 "saved_objectives": [
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  [
   900.0,
   90.0
  ]
 ]
}
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Content-Type: application/json

{
 "success": true,
 "message": "Necessary objects imported.",
 "tester": 3,
 "parameterNames": [
  "Destination distance (km)",
  "Number of days"
 ],
 "solution": [
  1850.0,
  7.0
 ],
 "objectives": [
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ]
 ],
 "bad_solutions": [],
 "saved_solutions": [
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  [
   1850.0,
   7.0
  ]
 ],
 "saved_objectives": [
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  [
   900.0,
   90.0
  ]
 ]
}
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Content-Type: application/json

{
 "success": true,
 "message": "Necessary objects imported.",
 "tester": 3,
 "parameterNames": [
  "Destination distance (km)",
  "Number of days"
 ],
 "solution": [
  1850.0,
  7.0
 ],
 "objectives": [
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ]
 ],
 "bad_solutions": [],
 "saved_solutions": [
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  [
   1850.0,
   7.0
  ]
 ],
 "saved_objectives": [
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  [
   900.0,
   90.0
  ]
 ]
}
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0.0000e+00, 1.1102e-16], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0.0000e+00, 1.1102e-16], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Content-Type: application/json

{
 "success": true,
 "message": "Necessary objects imported.",
 "tester": 3,
 "parameterNames": [
  "Destination distance (km)",
  "Number of days"
 ],
 "solution": [
  1850.0,
  7.0
 ],
 "objectives": [
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ]
 ],
 "bad_solutions": [],
 "saved_solutions": [
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  [
   1850.0,
   7.0
  ]
 ],
 "saved_objectives": [
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  [
   900.0,
   90.0
  ]
 ]
}
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0.0000e+00, 1.1102e-16], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Content-Type: application/json

{
 "success": true,
 "message": "Necessary objects imported.",
 "tester": 3,
 "parameterNames": [
  "Destination distance (km)",
  "Number of days"
 ],
 "solution": [
  1850.0,
  7.0
 ],
 "objectives": [
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ],
  [
   900.0,
   90.0
  ]
 ],
 "bad_solutions": [],
 "saved_solutions": [
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  "1850",
  "7",
  [
   1850.0,
   7.0
  ]
 ],
 "saved_objectives": [
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  "900",
  "90",
  [
   900.0,
   90.0
  ]
 ]
}
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0.0000e+00, 1.1102e-16], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([ 0.0000e+00, -1.1657e-15], dtype=torch.float64), std = tensor([0.0000, 1.0000], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([ 0.0000e+00, -4.4409e-16], dtype=torch.float64), std = tensor([0.0000, 1.0000], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 288, in <module>
    fit_gpytorch_model(mll)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 164, in fit_gpytorch_model
    mll = fit_gpytorch_mll(
          ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 105, in fit_gpytorch_mll
    return FitGPyTorchMLL(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/dispatcher.py", line 93, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 252, in _fit_fallback
    optimizer(mll, closure=closure, **optimizer_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/fit.py", line 92, in fit_gpytorch_mll_scipy
    result = scipy_minimize(
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/core.py", line 109, in scipy_minimize
    raw = minimize_with_timeout(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/utils/timeout.py", line 80, in minimize_with_timeout
    return optimize.minimize(
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_lbfgsb_py.py", line 307, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 383, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
             ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 77, in __call__
    self._compute_if_needed(x, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 71, in _compute_if_needed
    fg = self.fun(x, *args)
         ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 160, in __call__
    value, grads = _handle_numerical_errors(e, x=self.state, dtype=np_float64)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/utils/common.py", line 52, in _handle_numerical_errors
    raise error  # pragma: nocover
    ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 150, in __call__
    value_tensor, grad_tensors = self.closure(**kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 64, in __call__
    values = self.forward(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/model_closures.py", line 176, in closure
    log_likelihood = mll(
                     ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/module.py", line 31, in __call__
    outputs = self.forward(*inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 64, in forward
    res = output.log_prob(target)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py", line 171, in log_prob
    return super().log_prob(value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/distributions/multivariate_normal.py", line 248, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/distributions/multivariate_normal.py", line 58, in _batch_mahalanobis
    flat_L = bL.reshape(-1, n, n)  # shape = b x n x n
             ^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[-1, 9, 9]' is invalid for input of size 2
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 288, in <module>
    fit_gpytorch_model(mll)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 164, in fit_gpytorch_model
    mll = fit_gpytorch_mll(
          ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 105, in fit_gpytorch_mll
    return FitGPyTorchMLL(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/dispatcher.py", line 93, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 252, in _fit_fallback
    optimizer(mll, closure=closure, **optimizer_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/fit.py", line 92, in fit_gpytorch_mll_scipy
    result = scipy_minimize(
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/core.py", line 109, in scipy_minimize
    raw = minimize_with_timeout(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/utils/timeout.py", line 80, in minimize_with_timeout
    return optimize.minimize(
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_lbfgsb_py.py", line 307, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 383, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
             ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 77, in __call__
    self._compute_if_needed(x, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 71, in _compute_if_needed
    fg = self.fun(x, *args)
         ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 160, in __call__
    value, grads = _handle_numerical_errors(e, x=self.state, dtype=np_float64)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/utils/common.py", line 52, in _handle_numerical_errors
    raise error  # pragma: nocover
    ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 150, in __call__
    value_tensor, grad_tensors = self.closure(**kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 64, in __call__
    values = self.forward(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/model_closures.py", line 176, in closure
    log_likelihood = mll(
                     ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/module.py", line 31, in __call__
    outputs = self.forward(*inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 64, in forward
    res = output.log_prob(target)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py", line 171, in log_prob
    return super().log_prob(value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/distributions/multivariate_normal.py", line 248, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/distributions/multivariate_normal.py", line 58, in _batch_mahalanobis
    flat_L = bL.reshape(-1, n, n)  # shape = b x n x n
             ^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[-1, 2, 2]' is invalid for input of size 2
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 288, in <module>
    fit_gpytorch_model(mll)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 164, in fit_gpytorch_model
    mll = fit_gpytorch_mll(
          ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 105, in fit_gpytorch_mll
    return FitGPyTorchMLL(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/dispatcher.py", line 93, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/fit.py", line 252, in _fit_fallback
    optimizer(mll, closure=closure, **optimizer_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/fit.py", line 92, in fit_gpytorch_mll_scipy
    result = scipy_minimize(
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/core.py", line 109, in scipy_minimize
    raw = minimize_with_timeout(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/utils/timeout.py", line 80, in minimize_with_timeout
    return optimize.minimize(
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_lbfgsb_py.py", line 307, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 383, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
             ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 77, in __call__
    self._compute_if_needed(x, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 71, in _compute_if_needed
    fg = self.fun(x, *args)
         ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 160, in __call__
    value, grads = _handle_numerical_errors(e, x=self.state, dtype=np_float64)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/utils/common.py", line 52, in _handle_numerical_errors
    raise error  # pragma: nocover
    ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 150, in __call__
    value_tensor, grad_tensors = self.closure(**kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/core.py", line 64, in __call__
    values = self.forward(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/closures/model_closures.py", line 176, in closure
    log_likelihood = mll(
                     ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/module.py", line 31, in __call__
    outputs = self.forward(*inputs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 64, in forward
    res = output.log_prob(target)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py", line 171, in log_prob
    return super().log_prob(value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/distributions/multivariate_normal.py", line 248, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/distributions/multivariate_normal.py", line 58, in _batch_mahalanobis
    flat_L = bL.reshape(-1, n, n)  # shape = b x n x n
             ^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[-1, 2, 2]' is invalid for input of size 2
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 290, in <module>
    qehvi_sampler = SobolQMCNormalSampler(num_samples=MC_SAMPLES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MCSampler.__init__() missing 1 required positional argument: 'sample_shape'
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 290, in <module>
    qehvi_sampler = SobolQMCNormalSampler(num_samples=MC_SAMPLES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MCSampler.__init__() missing 1 required positional argument: 'sample_shape'
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 366, in <module>
    qehvi_sampler = SobolQMCNormalSampler(num_samples=MC_SAMPLES)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MCSampler.__init__() missing 1 required positional argument: 'sample_shape'
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([ 0.0000e+00, -1.1102e-16], dtype=torch.float64), std = tensor([0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_prediction_strategies.py", line 47, in __init__
    train_labels = train_labels.reshape(
                   ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[2, 4]' is invalid for input of size 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 293, in <module>
    new_x, new_x_actual = optimize_qehvi(model, train_obj, qehvi_sampler)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 212, in optimize_qehvi
    candidates, _ = optimize_acqf(
                    ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/optimize.py", line 563, in optimize_acqf
    return _optimize_acqf(opt_acqf_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/optimize.py", line 584, in _optimize_acqf
    return _optimize_acqf_batch(opt_inputs=opt_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/optimize.py", line 274, in _optimize_acqf_batch
    batch_initial_conditions = opt_inputs.get_ic_generator()(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/initializers.py", line 417, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(
                 ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/transforms.py", line 305, in decorated
    return method(cls, X, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/transforms.py", line 259, in decorated
    output = method(acqf, X, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 318, in forward
    posterior = self.model.posterior(X)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gpytorch.py", line 383, in posterior
    mvn = self(X)
          ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_gp.py", line 294, in __call__
    self.prediction_strategy = prediction_strategy(
                               ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_prediction_strategies.py", line 37, in prediction_strategy
    return cls(train_inputs, train_prior_dist, train_labels, likelihood)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/kernels/scale_kernel.py", line 124, in prediction_strategy
    return self.base_kernel.prediction_strategy(train_inputs, train_prior_dist, train_labels, likelihood)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/kernels/kernel.py", line 445, in prediction_strategy
    return exact_prediction_strategies.DefaultPredictionStrategy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_prediction_strategies.py", line 51, in __init__
    raise RuntimeError(
RuntimeError: Flattening the training labels failed. The most common cause of this error is that the shapes of the prior mean and the training labels are mismatched. The shape of the train targets is torch.Size([2, 1]), while the reported shape of the mean is torch.Size([2, 4]).
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_prediction_strategies.py", line 47, in __init__
    train_labels = train_labels.reshape(
                   ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[2, 4]' is invalid for input of size 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 293, in <module>
    new_x, new_x_actual = optimize_qehvi(model, train_obj, qehvi_sampler)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 212, in optimize_qehvi
    candidates, _ = optimize_acqf(
                    ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/optimize.py", line 563, in optimize_acqf
    return _optimize_acqf(opt_acqf_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/optimize.py", line 584, in _optimize_acqf
    return _optimize_acqf_batch(opt_inputs=opt_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/optimize.py", line 274, in _optimize_acqf_batch
    batch_initial_conditions = opt_inputs.get_ic_generator()(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/initializers.py", line 417, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(
                 ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/transforms.py", line 305, in decorated
    return method(cls, X, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/transforms.py", line 259, in decorated
    output = method(acqf, X, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 318, in forward
    posterior = self.model.posterior(X)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gpytorch.py", line 383, in posterior
    mvn = self(X)
          ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_gp.py", line 294, in __call__
    self.prediction_strategy = prediction_strategy(
                               ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_prediction_strategies.py", line 37, in prediction_strategy
    return cls(train_inputs, train_prior_dist, train_labels, likelihood)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/kernels/scale_kernel.py", line 124, in prediction_strategy
    return self.base_kernel.prediction_strategy(train_inputs, train_prior_dist, train_labels, likelihood)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/kernels/kernel.py", line 445, in prediction_strategy
    return exact_prediction_strategies.DefaultPredictionStrategy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpytorch/models/exact_prediction_strategies.py", line 51, in __init__
    raise RuntimeError(
RuntimeError: Flattening the training labels failed. The most common cause of this error is that the shapes of the prior mean and the training labels are mismatched. The shape of the train targets is torch.Size([2, 1]), while the reported shape of the mean is torch.Size([2, 4]).
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0.0000, 1.0000], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 243, in <module>
    reply2['test'] = xx
                     ^^
NameError: name 'xx' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 404, in <module>
    sys.stdout.write(json.dumps(reply,indent=1))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SobolQMCNormalSampler is not JSON serializable
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0., 1.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 202, in <module>
    reply2['test'] = xx
                     ^^
NameError: name 'xx' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 202, in <module>
    reply2['test'] = xx
                     ^^
NameError: name 'xx' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 347, in <module>
    reply['success'] = success
                       ^^^^^^^
NameError: name 'success' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 263, in <module>
    train_x = torch.cat([train_x, new_x])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 14 but got size 2 for tensor number 1 in the list.
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 263, in <module>
    train_x = torch.cat([train_x, new_x])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 14 but got size 2 for tensor number 1 in the list.
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 263, in <module>
    train_x = torch.cat([train_x, new_x])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 14 but got size 2 for tensor number 1 in the list.
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0.0000, 1.0000], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([1.0000, 0.0000], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 372, in <module>
    sys.stdout.write(json.dumps(reply,indent=1))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 276, in <module>
    new_x, new_x_actual = optimize_qehvi(model, train_obj, qehvi_sampler)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 203, in optimize_qehvi
    while (checkForbiddenRegions(bad_solutions, new_x_actual) == False):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 141, in checkForbiddenRegions
    for y in range(parameterNames.length):
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'length'
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 276, in <module>
    new_x, new_x_actual = optimize_qehvi(model, train_obj, qehvi_sampler)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 203, in optimize_qehvi
    while (checkForbiddenRegions(bad_solutions, new_x_actual) == False):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 141, in checkForbiddenRegions
    for y in range(parameterNames.length):
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'length'
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 276, in <module>
    new_x, new_x_actual = optimize_qehvi(model, train_obj, qehvi_sampler)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 203, in optimize_qehvi
    while (checkForbiddenRegions(bad_solutions, new_x_actual) == False):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test.py", line 141, in checkForbiddenRegions
    for y in range(parameterNames.length):
                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'length'
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([0.0000, 1.0000], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements ])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements ])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 239, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 241, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 240, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 240, in <module>
    objectivesInput.append([obj_measurements])
                            ^^^^^^^^^^^^^^^^
NameError: name 'obj_measurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 240, in <module>
    objectivesInput.append([objectiveMeasurements])
                            ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'objectiveMeasurements' is not defined
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 245, in <module>
    train_obj_actual = torch.tensor(objectivesInput, dtype=torch.float64)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many dimensions 'str'
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 264, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 264, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 264, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 264, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 264, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 264, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 270, in <module>
    volume = hv.compute(pareto_y)
             ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/utils/multi_objective/hypervolume.py", line 201, in compute
    raise BotorchTensorDimensionError(
botorch.exceptions.errors.BotorchTensorDimensionError: pareto_Y must have the same number of objectives as ref_point. Got 3, expected 2.
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 247, in <module>
    train_obj_actual = torch.tensor(objectivesInput, dtype=torch.float64)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected sequence of length 2 at dim 1 (got 3)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 247, in <module>
    train_obj_actual = torch.tensor(objectivesInput, dtype=torch.float64)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected sequence of length 2 at dim 1 (got 3)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0., 0.], dtype=torch.float64), std = tensor([0., 0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/initializers.py:432: BadInitialCandidatesWarning: Unable to find non-zero acquisition function values - initial conditions are being selected randomly.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0., 0.], dtype=torch.float64), std = tensor([0., 0., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/optim/initializers.py:432: BadInitialCandidatesWarning: Unable to find non-zero acquisition function values - initial conditions are being selected randomly.
  warnings.warn(
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 80, in <module>
    obj =  float(objective_Measurements)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'list'
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 266, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 266, in <module>
    mll, model = initialize_model(train_x, train_obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 181, in initialize_model
    model = SingleTaskGP(train_x, train_obj, outcome_transform=Standardize(m=train_obj.shape[-1]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/gp_regression.py", line 160, in __init__
    train_Y, train_Yvar = outcome_transform(train_Y, train_Yvar)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/transforms/outcome.py", line 294, in forward
    raise RuntimeError(
RuntimeError: Expected Y.shape[:-2] to be torch.Size([]), matching the `batch_shape` argument to `Standardize`, but got Y.shape[:-2]=torch.Size([1]).
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0.0000e+00, 0.0000e+00, 2.2204e-16], dtype=torch.float64), std = tensor([0., 0., 1.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
Traceback (most recent call last):
  File "/Applications/XAMPP/xamppfiles/htdocs/Demo/cgi/test_copy.py", line 80, in <module>
    obj = [float(x) for x in objective_Measurements]
                             ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'objective_Measurements' is not defined
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([0., 0.], dtype=torch.float64), std = tensor([1., 0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)
